'use strict';
(()=>{
const d=window.A1_DATA,$=id=>document.getElementById(id),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='slovak-a1-practice-v1',topicIds=new Set(d.modules.flatMap(m=>m.topics.map((t,i)=>`${m.id}-${i}`))),skillIds=new Set(d.skills.map(s=>s.id)),prodIds=new Set(d.production.map(p=>p.id));
function clean(raw){const out={topics:[],scores:{},drafts:{},checks:{},assessment:null};if(!raw||typeof raw!=='object')return out;out.topics=Array.isArray(raw.topics)?[...new Set(raw.topics.filter(x=>topicIds.has(x)))]:[];for(const [id,s] of Object.entries(raw.scores||{})){const total=skillIds.has(id)?d.skills.find(s=>s.id===id).questions.length:/^(?:grammar|listen-drill|listen-more)-(?:[1-9]|10)$/.test(id)?4:0;if(total&&Number.isInteger(s)&&s>=0&&s<=total)out.scores[id]=s}for(const id of prodIds){if(typeof raw.drafts?.[id]==='string')out.drafts[id]=raw.drafts[id].slice(0,5000);if(Array.isArray(raw.checks?.[id]))out.checks[id]=raw.checks[id].filter(n=>Number.isInteger(n)&&n>=0&&n<4)}if(raw.assessment&&['reading','listening'].every(k=>Number.isInteger(raw.assessment[k])&&raw.assessment[k]>=0&&raw.assessment[k]<=10))out.assessment={reading:raw.assessment.reading,listening:raw.assessment.listening};return out}
let state=clean(null),storageOK=true,route='',submitted=false;
try{state=clean(JSON.parse(localStorage.getItem(key)||'null'))}catch{storageOK=false}
function save(){try{localStorage.setItem(key,JSON.stringify(state));storageOK=true}catch{storageOK=false;const n=$('save-warning');if(n)n.textContent='Browser storage is unavailable. Export a backup before leaving.'}}
const normalize=s=>s.normalize('NFC').toLocaleLowerCase('sk').replace(/[.,!?;:„“”"’]/g,'').replace(/\s+/g,' ').trim();
function checkRecall(value,target){return normalize(value)===normalize(target)}
function audioTools(){return `<div class="toolbar"><button data-do="stop-audio">Stop audio</button><label>Speed <select id="audio-speed"><option value="0.7">0.7×</option><option value="0.85">0.85×</option><option value="1" selected>1×</option><option value="1.15">1.15×</option></select></label></div><p id="audio-status" role="status">Generated Slovak practice audio.</p>`}
function nav(){return `<aside class="learn-side"><p class="eyebrow">YOUR A1 PRACTICE</p>${[['path','Learning path'],['listening','Listening'],['reading','Reading'],['review','Review mistakes'],['assessment','A1 practice check'],['progress','Progress & backup']].map(([id,label])=>`<a href="#${id}" ${route===id?'aria-current="page"':''}>${label}</a>`).join('')}<a href="vocabulary.html">Everyday 1,000 flashcards ↗</a><a href="index.html">90-day vocabulary course ↗</a></aside>`}
function path(){return `<section class="help"><h2>Make your next session count</h2><a href="#review">Review missed activities & find your next lesson →</a></section><p class="eyebrow">TEN LESSONS · GRAMMAR, READING & LISTENING</p><h1>Build your Slovak, step by step.</h1><p>For each lesson: study the English grammar help, try the exercises, listen to the practice passages, then use the language yourself.</p><div class="learning-grid">${d.modules.map(m=>`<article class="learning-card"><p class="eyebrow">LESSON ${String(m.id).padStart(2,'0')}</p><h2>${E(m.title)}</h2><p>${E(m.goal)}</p><a href="#module-${m.id}">Open lesson →</a><small>${m.topics.filter((t,i)=>state.topics.includes(`${m.id}-${i}`)).length} / ${m.topics.length} topics marked studied · ${state.scores['grammar-'+m.id]??'—'} / 4 latest grammar score</small></article>`).join('')}</div><p class="muted">These are original learning activities. Study completion does not certify A1 proficiency.</p>`}
function question(q,id){return `<fieldset><legend>${E(q.prompt||q.question)}</legend>${q.options.map((o,i)=>`<label class="option"><input type="radio" name="${id}" value="${i}" required>${E(o)}</label>`).join('')}<div id="feedback-${id}"></div></fieldset>`}
function moduleView(id){const m=d.modules.find(x=>x.id===id);if(!m)return path();return `<p class="eyebrow">LESSON ${id}</p><h1>${E(m.title)}</h1><p>${E(m.goal)}</p><div class="section-links"><a href="#skill-listening-${id}">Listening →</a><a href="#skill-reading-${id}">Reading →</a></div>${audioTools()}${m.topics.map((t,i)=>`<section class="topic"><h2>${i+1}. ${E(t.title)}</h2><p>${E(t.rule)}</p><div class="examples">${t.examples.map((ex,j)=>`<p lang="sk">${E(ex[0])} <button data-do="example" data-unit="${id}" data-topic="${i}" data-example="${j}" aria-label="Listen to example ${j+1} of ${E(t.title)}">▶ Listen</button></p><p class="english-hint">${E(ex[1])}</p>`).join('')}</div><button data-do="studied" data-id="${id}-${i}" aria-pressed="${state.topics.includes(`${id}-${i}`)}">${state.topics.includes(`${id}-${i}`)?'✓ Studied · undo':'Mark topic studied'}</button><details><summary>Recall the first example</summary><p>Write the Slovak sentence for: ${E(t.examples[0][1])}</p><label for="recall-${id}-${i}">Your Slovak sentence</label><input class="recall" id="recall-${id}-${i}" autocomplete="off" spellcheck="false"><button data-do="recall" data-unit="${id}" data-topic="${i}">Check against example</button><div id="recall-feedback-${id}-${i}" role="status"></div><p class="muted">This checks the example’s wording. Other correct translations may exist. Diacritics count; case and punctuation do not.</p></details></section>`).join('')}<form id="quiz" class="exercise" data-kind="grammar" data-id="${id}"><h2>Check your understanding</h2>${m.topics.map((q,i)=>question(q,'q'+i)).join('')}<button class="primary" type="submit">Check answers</button><div id="quiz-result" role="status"></div></form><section class="help"><h2>Train your listening</h2><a href="#listen-drill-${id}">Listen and fill the missing words →</a></section>${id<10?`<a href="#module-${id+1}">Next lesson →</a>`:'<a href="#assessment">Try the A1 practice check →</a>'}`}
function skillsList(type){return `<h1>${type==='reading'?'Read for meaning':'Listen for meaning'}</h1><p>${type==='reading'?'Read a short Slovak message and find the important details.':'Listen before reading. You can replay each recording and slow it down.'}</p>${type==='listening'?'<div class="section-links"><a href="#listen-drill-1">New: listen & complete · 80 exercises →</a></div><h2>Passage comprehension</h2>':''}<div class="learning-grid">${d.skills.filter(s=>s.type===type).map(s=>`<article class="learning-card"><p class="eyebrow">${s.bonus?'EXTRA READING':'LESSON'} ${s.unit}</p><h2>${E(s.title)}</h2><a href="#skill-${s.id}">Start ${type} →</a><small>Latest score: ${state.scores[s.id]??'—'} / ${s.questions.length}</small></article>`).join('')}</div>${type==='listening'?drillList():''}`}
function passage(s,assessment=false){return `<section class="${assessment?'exercise':''}"><h2>${E(s.title)}</h2>${s.type==='reading'?`<p class="skill-passage" lang="sk">${E(s.sk)}</p>`:`<button type="button" data-do="passage" data-id="${s.id}">▶ Play listening passage</button>`}${!assessment?`<div id="transcript"></div>`:''}</section>`}
function nextActivity(kind,id){
 const items=kind==='skill'?d.skills.filter(s=>s.type===d.skills.find(x=>x.id===id)?.type):d.modules;
 const index=items.findIndex(x=>String(x.id)===String(id)),next=items[index+1];
 if(index<0)return '';
 const label=kind==='skill'?items[index].type:'grammar';
 return next?`<a class="next-activity" href="#${kind==='skill'?'skill':'module'}-${next.id}">Next ${label} lesson →</a>`:'<a class="next-activity" href="#assessment">Try the A1 practice check →</a>';
}
function skillView(id){const s=d.skills.find(x=>x.id===id);if(!s)return path();return `<p class="eyebrow">LESSON ${s.unit} · ${s.type.toUpperCase()}</p><h1>${E(s.title)}</h1>${s.type==='listening'?audioTools():''}${passage(s)}<form id="quiz" class="exercise" data-kind="skill" data-id="${s.id}">${s.questions.map((q,i)=>question(q,'q'+i)).join('')}<button class="primary" type="submit">Check answers & reveal English</button><div id="quiz-result" role="status"></div></form><nav class="toolbar" aria-label="Practice navigation"><a href="#${s.type}">All ${s.type} lessons</a><a href="#module-${s.unit}">Lesson ${s.unit} grammar</a>${state.scores[s.id]!==undefined?nextActivity('skill',s.id):''}</nav>`}
function wordCount(s){return s.trim()?s.trim().split(/\s+/u).length:0}
function assessment(){return `<h1>Your A1 practice check</h1><p>Try these familiar course activities without opening the lessons. Listen as often as needed. The result is a practice snapshot, not a validated CEFR exam or certificate.</p><p>This check scores reading and listening automatically. It does not assess speaking or writing.</p>${audioTools()}<form id="assessment-form">${['reading','listening'].map(type=>`<h2>${type==='reading'?'Part 1 · Reading':'Part 2 · Listening'}</h2>${d.skills.filter(s=>s.type===type&&!s.bonus).map((s,i)=>`<div class="exercise">${passage(s,true)}${question(s.questions[i%2],type+'-'+i)}</div>`).join('')}`).join('')}<button class="primary" type="submit">Check reading & listening</button><div id="assessment-result" role="status"></div></form><p class="muted">A1 goals are informed by the <a href="https://www.coe.int/en/web/common-european-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale" target="_blank" rel="noopener">Council of Europe description</a>. A high score on familiar questions alone does not establish your level.</p>`}
function progress(){return `<h1>Your practice record</h1><div class="learning-grid"><section class="learning-card"><span class="metric">${state.topics.length} / 40</span><p>Grammar topics marked studied</p></section><section class="learning-card"><span class="metric">${Object.keys(state.scores).length} / 60</span><p>Grammar, reading, listening and audio drills attempted</p></section></div><h2>Latest practice check</h2><p>${state.assessment?`Reading: ${state.assessment.reading}/10 · Listening: ${state.assessment.listening}/10. This score covers reading and listening.`:'No practice check saved yet.'}</p><h2>Choose what to revisit</h2>${d.modules.map(m=>`<p><a href="#module-${m.id}">Lesson ${m.id}: ${E(m.title)}</a> · Grammar ${state.scores['grammar-'+m.id]??'—'}/4 · Reading ${state.scores['reading-'+m.id]??'—'}/2 · Listening ${state.scores['listening-'+m.id]??'—'}/2 · <a href="#listen-drill-${m.id}">Audio drill ${state.scores['listen-drill-'+m.id]??'—'}/4</a></p>`).join('')}<section class="production"><h2>Keep a backup</h2><p>This learning area saves on this browser/device. Export your progress before clearing browser data. Previously saved writing drafts are retained in backups. The 90-day course keeps its own separate progress record.</p><button data-do="export">Download learning backup</button><p><label for="import">Restore a learning backup (replaces this learning area’s progress)</label></p><input id="import" type="file" accept="application/json,.json"><p id="import-status" role="status"></p></section>`}
function render(){window.LearningAudio.stop();window.LearningAudio.speed(1);submitted=false;route=location.hash.slice(1)||'path';if(route==='workspace')route='path';let body;if(/^module-(?:[1-9]|10)$/.test(route))body=moduleView(Number(route.slice(7)));else if(route.startsWith('skill-'))body=skillView(route.slice(6));else if(/^listen-drill-(?:[1-9]|10)$/.test(route))body=drillView(Number(route.slice(13)));else if(route.startsWith('write-')){route='listening';body=skillsList('listening')}else if(route==='reading'||route==='listening')body=skillsList(route);else if(route==='production'){route='listening';body=skillsList('listening')}else if(/^listen-more-(?:[1-9]|10)$/.test(route))body=drillView(Number(route.slice(12)),1);else if(route==='review')body=reviewView();else if(route==='assessment')body=assessment();else if(route==='progress')body=progress();else body=path();$('learn-app').innerHTML=`<div class="learn-layout">${nav()}<main class="learn-main" id="workspace" tabindex="-1"><p id="save-warning" role="status">${storageOK?'':'Browser storage is unavailable. Export a backup before leaving.'}</p>${body}<p class="muted">English-supported practice · synthetic audio · <a href="learning-review.md" target="_blank">Content & verification notes</a></p></main></div>`;}
function focusResult(id){const n=$(id);n?.setAttribute?.('tabindex','-1');n?.scrollIntoView?.({block:'center',behavior:'instant'});n?.focus?.({preventScroll:true})}
function showFeedback(q,id,value){const ok=value!==null&&value!==''&&Number(value)===q.answer;for(const input of document.querySelectorAll?.('input[name="'+id+'"]')||[]){const label=input.closest('label');if(label){if(Number(input.value)===q.answer)label.classList.add('correct');else if(input.checked)label.classList.add('incorrect')}}const n=$('feedback-'+id);n.className='feedback '+(ok?'correct':'incorrect');n.textContent=`${ok?'Correct.':'Review this one.'} ${q.options[q.answer]} — ${q.why}`;return Number(ok)}
document.addEventListener('click',e=>{if(e.target.closest('a.skip')){e.preventDefault();$('workspace').focus();return}const b=e.target.closest('[data-do]');if(!b)return;const a=b.dataset.do;if(a==='stop-audio')window.LearningAudio.stop();else if(a==='example'){const m=d.modules.find(x=>x.id===Number(b.dataset.unit));window.LearningAudio.play([m.topics[Number(b.dataset.topic)].examples[Number(b.dataset.example)][0]])}else if(a==='passage'){const s=d.skills.find(x=>x.id===b.dataset.id);if(s)window.LearningAudio.play([s.sk])}else if(a==='studied'){const id=b.dataset.id;state.topics=state.topics.includes(id)?state.topics.filter(x=>x!==id):[...state.topics,id];save();b.setAttribute('aria-pressed',String(state.topics.includes(id)));b.textContent=state.topics.includes(id)?'✓ Studied · undo':'Mark topic studied'}else if(a==='recall'){const id=b.dataset.unit+'-'+b.dataset.topic,t=d.modules.find(m=>m.id===Number(b.dataset.unit)).topics[Number(b.dataset.topic)],value=$('recall-'+id).value,n=$('recall-feedback-'+id);n.className='feedback';n.textContent=!value.trim()?'Write a sentence first.':checkRecall(value,t.examples[0][0])?'Matches the example. Well done.':`Model: ${t.examples[0][0]} — Compare the words, endings and accents. A different valid translation may not match this exact-example check.`}else if(a==='export'){const blob=new Blob([JSON.stringify({version:1,...state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='slovak-learning-backup.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}});
document.addEventListener('change',async e=>{if(e.target.id==='audio-speed')window.LearningAudio.speed(e.target.value);else if(e.target.id==='import'){const file=e.target.files[0];if(!file)return;try{if(file.size>200000)throw Error();const raw=JSON.parse(await file.text());if(raw.version!==1||!Array.isArray(raw.topics)||!raw.scores||!raw.drafts)throw Error();state=clean(raw);save();render();$('import-status').textContent='Backup restored.'}catch{$('import-status').textContent='This is not a supported learning backup. Existing progress has been kept.'}}});
document.addEventListener('submit',e=>{if(e.target.id==='quiz'){e.preventDefault();if(submitted)return;const form=e.target,kind=form.dataset.kind,id=form.dataset.id,qs=kind==='grammar'?d.modules.find(m=>m.id===Number(id)).topics:d.skills.find(s=>s.id===id).questions,values=new FormData(form);if(qs.some((q,i)=>values.get('q'+i)===null)){ $('quiz-result').textContent='Answer every question before checking.';return}let score=0;qs.forEach((q,i)=>score+=showFeedback(q,'q'+i,values.get('q'+i)));state.scores[kind==='grammar'?'grammar-'+id:id]=score;save();submitted=true;form.querySelector('button[type=submit]').disabled=true;form.querySelectorAll('input[type=radio]').forEach(n=>n.disabled=true);$('quiz-result').innerHTML=`<p class="feedback">${score} / ${qs.length} correct. ${score===qs.length?'Try using these ideas in your own sentences.':'Read the explanations and revisit the lesson.'}</p><div class="toolbar"><button type="button" data-do="retry">Try again</button>${nextActivity(kind,id)}</div>`;if(kind==='skill'){const s=d.skills.find(x=>x.id===id);$('transcript').innerHTML=`<details open><summary>Transcript & English</summary><p lang="sk">${E(s.sk)}</p><p>${E(s.en)}</p></details>`}focusResult('quiz-result')}else if(e.target.id==='assessment-form'){e.preventDefault();if(submitted)return;const values=new FormData(e.target),result={reading:0,listening:0};for(const type of ['reading','listening'])d.skills.filter(s=>s.type===type&&!s.bonus).forEach((s,i)=>result[type]+=showFeedback(s.questions[i%2],type+'-'+i,values.get(type+'-'+i)));state.assessment=result;save();submitted=true;e.target.querySelector('button[type=submit]').disabled=true;e.target.querySelectorAll('input[type=radio]').forEach(n=>n.disabled=true);$('assessment-result').innerHTML=`<div class="feedback"><h2>Reading ${result.reading}/10 · Listening ${result.listening}/10</h2><p>Review any missed details using the separate skills activities. Try the missing-word listening drills for more practice. There is no official pass mark here.</p><button type="button" data-do="retry">Retake practice check</button></div>`;focusResult('assessment-result')}});
document.addEventListener('click',e=>{if(e.target.closest('[data-do="retry"]')){render();const id=route.startsWith('listen-')?'listening-drill':route==='assessment'?'assessment-form':'quiz';focusResult(id)}});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);$('workspace').focus()});window.addEventListener('pagehide',()=>window.LearningAudio.stop());

function listeningDrills(unit,round=0){const m=d.modules.find(m=>m.id===unit);return m?m.topics.map(t=>{const [sk,en]=t.examples[round],words=sk.split(/\s+/),index=words.findLastIndex(w=>/\p{L}/u.test(w));return {sk,en,answer:normalize(words[index]),gap:words.map((w,i)=>i===index?'_____':w).join(' ')}}):[]}
function drillNext(unit,round=0){const prefix=round?'listen-more-':'listen-drill-';return unit<10?'<a class="next-activity" href="#'+prefix+(unit+1)+'">Next listening drill →</a>':'<a class="next-activity" href="#listening">All listening activities →</a>'}
function drillList(){return '<h2>Listen for the missing word</h2><p>80 automatically checked exercises in two sets per lesson. Play the sentence, complete its missing word, then see corrections and English meanings.</p><div class="learning-grid">'+d.modules.map(m=>'<article class="learning-card"><p class="eyebrow">LESSON '+m.id+' · 4 AUDIO EXERCISES</p><h2>'+E(m.title)+'</h2><a href="#listen-drill-'+m.id+'">Start set 1 →</a><p><a href="#listen-more-'+m.id+'">Start set 2 →</a></p><small>Latest score: '+(state.scores['listen-drill-'+m.id]??'—')+' / 4 · Set 2: '+(state.scores['listen-more-'+m.id]??'—')+' / 4</small></article>').join('')+'</div>'}
function drillView(unit,round=0){const prefix=round?'listen-more-':'listen-drill-',qs=listeningDrills(unit,round);if(!qs.length)return skillsList('listening');return '<p class="eyebrow">LESSON '+unit+' · SET '+(round+1)+' · LISTEN & COMPLETE</p><h1>Catch the missing word</h1><p>Listen to each sentence and type the missing Slovak word. Replay or slow down the audio as needed. Case and punctuation are ignored; Slovak accents count.</p>'+audioTools()+'<form id="listening-drill" data-unit="'+unit+'" data-round="'+round+'">'+qs.map((q,i)=>'<section class="exercise"><h2>Sentence '+(i+1)+'</h2><button type="button" data-do="drill-play" data-unit="'+unit+'" data-round="'+round+'" data-index="'+i+'">▶ Listen to sentence '+(i+1)+'</button><p class="skill-passage" lang="sk">'+E(q.gap)+'</p><label for="drill-'+i+'">Missing word '+(i+1)+'</label><input class="recall" id="drill-'+i+'" name="word-'+i+'" lang="sk" required autocomplete="off" autocapitalize="none" spellcheck="false"><div id="drill-feedback-'+i+'" role="status"></div></section>').join('')+'<button class="primary" type="submit">Check all four answers</button><div id="drill-result" role="status"></div></form><nav class="toolbar" aria-label="Listening navigation"><a href="#listening">All listening activities</a><a href="#skill-listening-'+unit+'">Listen to a longer passage →</a>'+(state.scores[prefix+unit]!==undefined?drillNext(unit,round):'')+'</nav>'}
document.addEventListener('click',e=>{const b=e.target.closest('[data-do="drill-play"]');if(b){const q=listeningDrills(Number(b.dataset.unit),Number(b.dataset.round)||0)[Number(b.dataset.index)];if(q)window.LearningAudio.play([q.sk])}});
document.addEventListener('submit',e=>{if(e.target.id!=='listening-drill')return;e.preventDefault();if(submitted)return;const unit=Number(e.target.dataset.unit),round=Number(e.target.dataset.round)||0,qs=listeningDrills(unit,round),values=new FormData(e.target);if(qs.some((q,i)=>!String(values.get('word-'+i)||'').trim())){$('drill-result').textContent='Fill in all four missing words first.';return}let score=0;qs.forEach((q,i)=>{const answer=String(values.get('word-'+i)),ok=checkRecall(answer,q.answer);score+=Number(ok);const n=$('drill-feedback-'+i);n.className='feedback '+(ok?'correct':'incorrect');n.innerHTML='<strong>'+(ok?'Correct.':'Not quite. Correct word: '+E(q.answer))+'</strong>'+(!ok?'<p>Your answer: '+E(answer)+'</p>':'')+'<p lang="sk">'+E(q.sk)+'</p><p>'+E(q.en)+'</p>'});state.scores[(round?'listen-more-':'listen-drill-')+unit]=score;save();submitted=true;e.target.querySelector('button[type=submit]').disabled=true;e.target.querySelectorAll('input').forEach(n=>n.disabled=true);$('drill-result').innerHTML='<p class="feedback">'+score+' / 4 correct. '+(score===4?'All four words matched the recording.':'Replay the sentences and review the corrected words above.')+'</p><div class="toolbar"><button type="button" data-do="retry">Try again</button>'+drillNext(unit,round)+'</div>';focusResult('drill-result')});


function reviewView(){const tasks=[...d.modules.map(m=>({id:'grammar-'+m.id,title:m.title,href:'module-'+m.id,total:4})),...d.skills.map(s=>({id:s.id,title:s.title,href:'skill-'+s.id,total:s.questions.length})),...[0,1].flatMap(round=>d.modules.map(m=>({id:(round?'listen-more-':'listen-drill-')+m.id,title:'Listening '+m.id+' · set '+(round+1),href:(round?'listen-more-':'listen-drill-')+m.id,total:4})))];const missed=tasks.filter(t=>state.scores[t.id]!==undefined&&state.scores[t.id]<t.total),fresh=tasks.filter(t=>state.scores[t.id]===undefined);return '<h1>Your next useful practice</h1><p>Revisit activities where your latest score has missed answers, then try something new. A full score removes an activity from this review list.</p><h2>Needs another look · '+missed.length+'</h2><div class="learning-grid">'+(missed.map(t=>'<article class="learning-card"><h2>'+E(t.title)+'</h2><p>'+state.scores[t.id]+' / '+t.total+' correct</p><a href="#'+t.href+'">Review activity →</a></article>').join('')||'<p>No missed activities saved. Try a new activity below.</p>')+'</div><h2>Try something new</h2><div class="learning-grid">'+fresh.slice(0,6).map(t=>'<article class="learning-card"><h2>'+E(t.title)+'</h2><a href="#'+t.href+'">Start →</a></article>').join('')+'</div>'}

// Exposed pure helpers support regression checks without changing learner state.
window.A1Checks={clean,normalize,checkRecall,wordCount,listeningDrills};render();
})();
